-- phpMyAdmin SQL Dump
-- version 4.8.3
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Dec 11, 2019 at 08:53 PM
-- Server version: 5.7.23
-- PHP Version: 7.2.10

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `poseidon`
--

-- --------------------------------------------------------

--
-- Table structure for table `rooms`
--

DROP TABLE IF EXISTS `rooms`;
CREATE TABLE IF NOT EXISTS `rooms` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `hotel_id` int(11) NOT NULL,
  `room_number` int(11) NOT NULL,
  `description` text NOT NULL,
  `max_adults` int(11) NOT NULL,
  `max_children` int(11) NOT NULL DEFAULT '0',
  `room_type_id` int(11) NOT NULL,
  `no_bathrooms` int(11) NOT NULL,
  `smoking` tinyint(1) NOT NULL,
  `featured` tinyint(1) DEFAULT '0',
  `room_cost` decimal(18,2) NOT NULL,
  `deleted_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_room_hotel` (`hotel_id`),
  KEY `fk_room_room_type` (`room_type_id`)
) ENGINE=InnoDB AUTO_INCREMENT=62 DEFAULT CHARSET=utf8mb4 COMMENT='Table that manages room information';

--
-- Dumping data for table `rooms`
--

INSERT INTO `rooms` (`id`, `hotel_id`, `room_number`, `description`, `max_adults`, `max_children`, `room_type_id`, `no_bathrooms`, `smoking`, `featured`, `room_cost`, `deleted_at`, `created_at`, `updated_at`) VALUES
(1, 1, 101, 'Panoramic views from the highest floors of the hotel\r\n\r\nIn the Oceanfront Superior Junior Suite, you’ll have the vast Caribbean Sea at your feet. Have a relaxing soak in the whirlpool tub on your private balcony, and admire the views from the hotel’s greatest heights while indulging in a drink from your customized minibar. Inside your room, you’ll find more exclusive comforts and amenities. In fact, exclusivity awaits you throughout the entire resort. Enjoy access to the private beach club as well as the butler service at both the beach and pool, all of which will make your next vacation in Cancún simply unforgettable.\r\n', 2, 0, 18, 2, 1, 0, '1200.00', NULL, '2019-11-27 09:36:37', '2019-12-11 17:13:52'),
(2, 1, 102, 'Panoramic views from the highest floors of the hotel\r\n\r\nIn the Oceanfront Superior Junior Suite, you’ll have the vast Caribbean Sea at your feet. Have a relaxing soak in the whirlpool tub on your private balcony, and admire the views from the hotel’s greatest heights while indulging in a drink from your customized minibar. Inside your room, you’ll find more exclusive comforts and amenities. In fact, exclusivity awaits you throughout the entire resort. Enjoy access to the private beach club as well as the butler service at both the beach and pool, all of which will make your next vacation in Cancún simply unforgettable.', 2, 2, 18, 2, 0, 0, '1200.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:16:03'),
(3, 1, 103, 'Panoramic views from the highest floors of the hotel\r\n\r\nIn the Oceanfront Superior Junior Suite, you’ll have the vast Caribbean Sea at your feet. Have a relaxing soak in the whirlpool tub on your private balcony, and admire the views from the hotel’s greatest heights while indulging in a drink from your customized minibar. Inside your room, you’ll find more exclusive comforts and amenities. In fact, exclusivity awaits you throughout the entire resort. Enjoy access to the private beach club as well as the butler service at both the beach and pool, all of which will make your next vacation in Cancún simply unforgettable.', 2, 2, 18, 2, 0, 0, '1200.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:16:55'),
(4, 1, 104, 'Panoramic views from the highest floors of the hotel\r\n\r\nIn the Oceanfront Superior Junior Suite, you’ll have the vast Caribbean Sea at your feet. Have a relaxing soak in the whirlpool tub on your private balcony, and admire the views from the hotel’s greatest heights while indulging in a drink from your customized minibar. Inside your room, you’ll find more exclusive comforts and amenities. In fact, exclusivity awaits you throughout the entire resort. Enjoy access to the private beach club as well as the butler service at both the beach and pool, all of which will make your next vacation in Cancún simply unforgettable.', 2, 2, 18, 2, 0, 0, '1200.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:17:09'),
(5, 1, 105, 'For those who love a good view and space to stretch out\r\n\r\nImagine opening your eyes each morning to the sight of the Caribbean and enjoying sea views from every corner of your room. In the Oceanfront Corner Junior Suite, you’ll never lose sight of the sea thanks to the room’s corner position and the 280 square-foot wraparound terrace. The terrace’s hot tub makes for an even more inviting sanctuary. Both the room and the hotel offer an endless array of services and comforts to make your vacation in Cancún a world of true exclusivity..', 2, 0, 24, 1, 1, 0, '800.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:19:04'),
(6, 1, 201, 'For those who love a good view and space to stretch out\r\n\r\nImagine opening your eyes each morning to the sight of the Caribbean and enjoying sea views from every corner of your room. In the Oceanfront Corner Junior Suite, you’ll never lose sight of the sea thanks to the room’s corner position and the 280 square-foot wraparound terrace. The terrace’s hot tub makes for an even more inviting sanctuary. Both the room and the hotel offer an endless array of services and comforts to make your vacation in Cancún a world of true exclusivity.', 2, 2, 24, 1, 0, 0, '800.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:19:16'),
(7, 1, 202, 'For those who love a good view and space to stretch out\r\n\r\nImagine opening your eyes each morning to the sight of the Caribbean and enjoying sea views from every corner of your room. In the Oceanfront Corner Junior Suite, you’ll never lose sight of the sea thanks to the room’s corner position and the 280 square-foot wraparound terrace. The terrace’s hot tub makes for an even more inviting sanctuary. Both the room and the hotel offer an endless array of services and comforts to make your vacation in Cancún a world of true exclusivity.', 2, 2, 24, 1, 0, 0, '800.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:19:26'),
(8, 1, 203, 'For those who love a good view and space to stretch out\r\n\r\nImagine opening your eyes each morning to the sight of the Caribbean and enjoying sea views from every corner of your room. In the Oceanfront Corner Junior Suite, you’ll never lose sight of the sea thanks to the room’s corner position and the 280 square-foot wraparound terrace. The terrace’s hot tub makes for an even more inviting sanctuary. Both the room and the hotel offer an endless array of services and comforts to make your vacation in Cancún a world of true exclusivity.', 2, 2, 24, 1, 0, 0, '800.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:19:41'),
(9, 1, 204, 'For those who want to cool off in a private pool\r\n\r\nWhile staying in the Oceanfront Rooftop Junior Suite, you can go for a dip in the private pool of your room’s rooftop terrace and relax to the rocking of the waves from the top of the hotel. Take in views of the Caribbean while lying back on the sun loungers, or simply unwind knowing that the hotel offers all the comforts you need for a perfect vacation.', 2, 0, 21, 1, 1, 0, '750.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:21:22'),
(10, 1, 205, 'For those who want to cool off in a private pool\r\n\r\nWhile staying in the Oceanfront Rooftop Junior Suite, you can go for a dip in the private pool of your room’s rooftop terrace and relax to the rocking of the waves from the top of the hotel. Take in views of the Caribbean while lying back on the sun loungers, or simply unwind knowing that the hotel offers all the comforts you need for a perfect vacation.', 2, 0, 21, 1, 1, 0, '750.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:21:39'),
(11, 1, 301, 'For those who want to cool off in a private pool\r\n\r\nWhile staying in the Oceanfront Rooftop Junior Suite, you can go for a dip in the private pool of your room’s rooftop terrace and relax to the rocking of the waves from the top of the hotel. Take in views of the Caribbean while lying back on the sun loungers, or simply unwind knowing that the hotel offers all the comforts you need for a perfect vacation..', 2, 2, 21, 1, 0, 0, '750.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:21:54'),
(12, 1, 302, 'For those who want to cool off in a private pool\r\n\r\nWhile staying in the Oceanfront Rooftop Junior Suite, you can go for a dip in the private pool of your room’s rooftop terrace and relax to the rocking of the waves from the top of the hotel. Take in views of the Caribbean while lying back on the sun loungers, or simply unwind knowing that the hotel offers all the comforts you need for a perfect vacation..', 2, 2, 21, 1, 0, 0, '750.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:22:09'),
(13, 1, 303, 'For those who love taking in ocean views from up high\r\n\r\nThe Oceanfront Superior Suite​ is located on the highest floors of the hotel, so you can enjoy a tranquil panoramic view of the Caribbean from your very own terrace. Inside, luxury and comfort await, with Grand service, a butler service, and much more. The Suite is located close to the beach and main swimming pool, so that you can be in the water in a matter of seconds.  ', 2, 0, 19, 2, 1, 0, '1050.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:25:58'),
(14, 1, 304, 'For those who love taking in ocean views from up high\r\n\r\nThe Oceanfront Superior Suite​ is located on the highest floors of the hotel, so you can enjoy a tranquil panoramic view of the Caribbean from your very own terrace. Inside, luxury and comfort await, with Grand service, a butler service, and much more. The Suite is located close to the beach and main swimming pool, so that you can be in the water in a matter of seconds.  ', 2, 2, 19, 2, 0, 0, '1050.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:26:15'),
(15, 1, 305, 'Elegance, privacy and spaciousness\r\n\r\nThe Villas are located in a remote area of the complex and each feature a private pool and garden for greater privacy. Offering 2,088 ft² of pure luxury and elegance, the Villas include one bedroom, a balcony where you can have a soak in the whirlpool bath, a living room, and a spacious terrace with sun loungers and deckchairs by the pool. The Grand Star service offers you some extra perks, such as in-room check-in, as well as private transport throughout the complex, and our butler service will help with anything you need, so you can create your perfect vacation experience..', 4, 0, 23, 1, 1, 0, '850.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:27:23'),
(16, 1, 401, 'Elegance, privacy and spaciousness\r\n\r\nThe Villas are located in a remote area of the complex and each feature a private pool and garden for greater privacy. Offering 2,088 ft² of pure luxury and elegance, the Villas include one bedroom, a balcony where you can have a soak in the whirlpool bath, a living room, and a spacious terrace with sun loungers and deckchairs by the pool. The Grand Star service offers you some extra perks, such as in-room check-in, as well as private transport throughout the complex, and our butler service will help with anything you need, so you can create your perfect vacation experience.', 4, 0, 23, 1, 1, 0, '850.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:27:34'),
(17, 1, 402, 'Elegance, privacy and spaciousness\r\n\r\nThe Villas are located in a remote area of the complex and each feature a private pool and garden for greater privacy. Offering 2,088 ft² of pure luxury and elegance, the Villas include one bedroom, a balcony where you can have a soak in the whirlpool bath, a living room, and a spacious terrace with sun loungers and deckchairs by the pool. The Grand Star service offers you some extra perks, such as in-room check-in, as well as private transport throughout the complex, and our butler service will help with anything you need, so you can create your perfect vacation experience.', 4, 0, 23, 1, 0, 0, '850.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:27:52'),
(18, 1, 403, 'Elegance, privacy and spaciousness\r\n\r\nThe Villas are located in a remote area of the complex and each feature a private pool and garden for greater privacy. Offering 2,088 ft² of pure luxury and elegance, the Villas include one bedroom, a balcony where you can have a soak in the whirlpool bath, a living room, and a spacious terrace with sun loungers and deckchairs by the pool. The Grand Star service offers you some extra perks, such as in-room check-in, as well as private transport throughout the complex, and our butler service will help with anything you need, so you can create your perfect vacation experience.', 0, 4, 23, 1, 0, 0, '850.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:28:05'),
(19, 1, 404, 'Elegance with garden views\r\n\r\nIn the Suite you’re guaranteed an elegant Caribbean vacation at one of the Riviera Maya’s most exclusive complexes for adults only. A concierge will assist you with your every request, while our gourmet room service is sure to exceed your expectations, 24 hours a day.  The spacious private terrace boasts views overlooking the lush tropical vegetation of the jungle and gardens that surround the hotel. .', 1, 1, 25, 1, 0, 0, '530.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:29:38'),
(20, 1, 405, 'Maximum elegance and comfort in a one-of-a-kind environment\r\n\r\nIn the Presidential Suite, you’re in for an elegant vacation experience, starting with over 2,500 ft² of pure luxury and comfort at your disposal. Amenities include a private terrace overlooking the sea, hydromassage tub, hammocks, a spacious bedroom with king-size bed, sitting room, dining area and kitchenette. You can enjoy the refreshing sea breeze, stunning ocean views, and an ambiance of total tranquility, all from the comfort of your room.  These unbeatable amenities are matched by nothing less than impeccable service. You personal concierge will help you create the vacation experience that’s perfect for you, while 24-hour room service prepares gourmet treats designed to delight your unique palate.', 2, 0, 22, 2, 0, 1, '1500.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:30:21'),
(21, 2, 101, 'Relaxing panoramic views of the jungle\r\n\r\nIn the Superior Suite, you’ll be treated to serene views of the surrounding jungle from one of the hotel’s highest floors. The room is located in the main building, which means you’ll have more convenient access to the hotel’s restaurants and services. Excellence awaits you both inside and outside the room, where everything is designed to cater to your wishes.  ', 2, 0, 17, 1, 1, 0, '650.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:31:19'),
(22, 2, 102, 'Relaxing panoramic views of the jungle\r\n\r\nIn the Superior Suite, you’ll be treated to serene views of the surrounding jungle from one of the hotel’s highest floors. The room is located in the main building, which means you’ll have more convenient access to the hotel’s restaurants and services. Excellence awaits you both inside and outside the room, where everything is designed to cater to your wishes.  ', 2, 0, 17, 1, 0, 0, '650.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:31:29'),
(23, 2, 103, 'For those who want the best Caribbean views\r\n\r\nIn the Oceanfront Corner Superior Suite, you’ll enjoy impeccable ocean views. Nestled in the corners of the building’s highest floors, these rooms offer panoramic views of the Caribbean whose natural beauty is truly breathtaking. You can also enjoy the tropical atmosphere from inside the hydromassage tub or hammocks on the private terrace. Inside, your experience is hallmarked by total comfort and luxury, with personal concierge services, Grand Star advantages, in-room check-in, and other delightful details.', 4, 4, 18, 2, 0, 0, '1200.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:32:24'),
(24, 2, 104, 'For those who want the best Caribbean views\r\n\r\nIn the Oceanfront Corner Superior Suite, you’ll enjoy impeccable ocean views. Nestled in the corners of the building’s highest floors, these rooms offer panoramic views of the Caribbean whose natural beauty is truly breathtaking. You can also enjoy the tropical atmosphere from inside the hydromassage tub or hammocks on the private terrace. Inside, your experience is hallmarked by total comfort and luxury, with personal concierge services, Grand Star advantages, in-room check-in, and other delightful details.', 4, 4, 18, 2, 0, 0, '1200.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:32:33'),
(25, 2, 105, 'For beach-lovers\r\n\r\nThe Oceanfront Suite faces the Caribbean Sea, so you can admire its waves from the terrace and go for a swim within a matter of minutes. The room’s interior is carefully designed with you in mind, with restful details like fine European bed linens, hydromassage tub, gourmet room service offered 24 hours a day… and personal concierge committed to helping you craft the perfect vacation experience for you.', 2, 2, 24, 1, 1, 0, '800.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:33:55'),
(26, 2, 201, 'For beach-lovers\r\n\r\nThe Oceanfront Suite faces the Caribbean Sea, so you can admire its waves from the terrace and go for a swim within a matter of minutes. The room’s interior is carefully designed with you in mind, with restful details like fine European bed linens, hydromassage tub, gourmet room service offered 24 hours a day… and personal concierge committed to helping you craft the perfect vacation experience for you.', 2, 2, 24, 1, 0, 0, '800.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:34:13'),
(27, 2, 202, 'For beach-lovers\r\n\r\nThe Oceanfront Suite faces the Caribbean Sea, so you can admire its waves from the terrace and go for a swim within a matter of minutes. The room’s interior is carefully designed with you in mind, with restful details like fine European bed linens, hydromassage tub, gourmet room service offered 24 hours a day… and personal concierge committed to helping you craft the perfect vacation experience for you.', 2, 2, 24, 1, 0, 0, '800.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:34:39'),
(28, 2, 203, 'For beach-lovers\r\n\r\nThe Oceanfront Suite faces the Caribbean Sea, so you can admire its waves from the terrace and go for a swim within a matter of minutes. The room’s interior is carefully designed with you in mind, with restful details like fine European bed linens, hydromassage tub, gourmet room service offered 24 hours a day… and personal concierge committed to helping you craft the perfect vacation experience for you.', 2, 2, 24, 1, 0, 0, '800.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:34:45'),
(29, 2, 204, 'For our guests who can’t get enough of the pool\r\n\r\nIn the Pool View Suite, you’ll have the hotel pool right in front of your room. The Suite is located on the hotel’s ground floor, so you can be in the water in a matter of minutes.  Our team brings your vacation experience to the next level with personal concierge service, a pillow menu, gourmet room service, and other luxurious details designed to meet your every need.', 2, 2, 21, 1, 1, 0, '750.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:35:47'),
(30, 2, 205, 'For our guests who can’t get enough of the pool\r\n\r\nIn the Pool View Suite, you’ll have the hotel pool right in front of your room. The Suite is located on the hotel’s ground floor, so you can be in the water in a matter of minutes.  Our team brings your vacation experience to the next level with personal concierge service, a pillow menu, gourmet room service, and other luxurious details designed to meet your every need.', 2, 2, 21, 1, 1, 0, '750.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:35:53'),
(31, 2, 301, 'For our guests who can’t get enough of the pool\r\n\r\nIn the Pool View Suite, you’ll have the hotel pool right in front of your room. The Suite is located on the hotel’s ground floor, so you can be in the water in a matter of minutes.  Our team brings your vacation experience to the next level with personal concierge service, a pillow menu, gourmet room service, and other luxurious details designed to meet your every need.', 2, 2, 21, 1, 0, 0, '750.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:36:02'),
(32, 2, 302, 'For our guests who can’t get enough of the pool\r\n\r\nIn the Pool View Suite, you’ll have the hotel pool right in front of your room. The Suite is located on the hotel’s ground floor, so you can be in the water in a matter of minutes.  Our team brings your vacation experience to the next level with personal concierge service, a pillow menu, gourmet room service, and other luxurious details designed to meet your every need.', 2, 2, 21, 1, 0, 0, '750.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:36:11'),
(33, 2, 303, 'For large families\r\n\r\nIn the Two Bedroom Family Junior Suite, you can enjoy two connecting Junior Suites so that your Jamaican vacation is one of absolute comfort. Along with relaxing garden views from its two private balconies, the room features a minibar, room service, turndown service, and more. Your hotel experience is all-inclusive: unmatched culinary experiences and limitless activities going on all day. And if you want to relax, the best place is the SPA Sensations, where you’ll have complimentary access to the hydrotherapy areas.', 2, 0, 19, 2, 1, 0, '1050.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:38:57'),
(34, 2, 304, 'For large families\r\n\r\nIn the Two Bedroom Family Junior Suite, you can enjoy two connecting Junior Suites so that your Jamaican vacation is one of absolute comfort. Along with relaxing garden views from its two private balconies, the room features a minibar, room service, turndown service, and more. Your hotel experience is all-inclusive: unmatched culinary experiences and limitless activities going on all day. And if you want to relax, the best place is the SPA Sensations, where you’ll have complimentary access to the hydrotherapy areas.', 2, 0, 19, 2, 0, 1, '1050.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:39:07'),
(35, 2, 305, 'For those who want the beach in their backyard\r\n\r\nThe Oceanfront Junior Suite features a panoramic view of the Caribbean so stunning you’ll want to commit it to memory. The room is also conveniently located close to both the beach and the hotel pool. Inside your room, we’ve taken care of everything you need to enjoy a once-in-a-lifetime vacation in Jamaica. When you venture outside, you’ll find a wide variety of cuisines, limitless leisure and sports activities, and pure relaxation at SPA Sensations, where you’ll enjoy complimentary access.', 4, 4, 23, 1, 1, 0, '850.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:40:00'),
(36, 2, 401, 'For those who want the beach in their backyard\r\n\r\nThe Oceanfront Junior Suite features a panoramic view of the Caribbean so stunning you’ll want to commit it to memory. The room is also conveniently located close to both the beach and the hotel pool. Inside your room, we’ve taken care of everything you need to enjoy a once-in-a-lifetime vacation in Jamaica. When you venture outside, you’ll find a wide variety of cuisines, limitless leisure and sports activities, and pure relaxation at SPA Sensations, where you’ll enjoy complimentary access.', 4, 4, 23, 1, 1, 0, '850.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:40:11'),
(37, 2, 402, 'For those who want the beach in their backyard\r\n\r\nThe Oceanfront Junior Suite features a panoramic view of the Caribbean so stunning you’ll want to commit it to memory. The room is also conveniently located close to both the beach and the hotel pool. Inside your room, we’ve taken care of everything you need to enjoy a once-in-a-lifetime vacation in Jamaica. When you venture outside, you’ll find a wide variety of cuisines, limitless leisure and sports activities, and pure relaxation at SPA Sensations, where you’ll enjoy complimentary access.', 4, 4, 23, 1, 0, 0, '850.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:40:39'),
(38, 2, 403, 'For those who want the beach in their backyard\r\n\r\nThe Oceanfront Junior Suite features a panoramic view of the Caribbean so stunning you’ll want to commit it to memory. The room is also conveniently located close to both the beach and the hotel pool. Inside your room, we’ve taken care of everything you need to enjoy a once-in-a-lifetime vacation in Jamaica. When you venture outside, you’ll find a wide variety of cuisines, limitless leisure and sports activities, and pure relaxation at SPA Sensations, where you’ll enjoy complimentary access.', 4, 4, 23, 1, 0, 0, '850.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:40:44'),
(39, 2, 404, 'For those looking for extra space\r\n\r\nIn the Junior Suite, you can enjoy relaxing views of the hotel garden from your private balcony. Within the room, we have taken care of absolutely everything so you can enjoy an unforgettable vacation both inside and outside of the room. The hotel’s facilities include broad culinary options and numerous activities. Adults may also enjoy complimentary access to the hydrotherapy areas of the SPA Sensations.', 1, 0, 25, 1, 0, 0, '530.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:42:21'),
(40, 2, 405, 'For those who love heights\r\n\r\nThe Premier Plus King rooms are located on the top floors so that you can take in all of South Beach from your hotel room. Just by stepping out onto your terrace, you can take in the pool, city and Atlantic Ocean.', 2, 0, 22, 2, 0, 0, '1500.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:45:15'),
(41, 3, 101, 'For those who prefer simplicity\r\n\r\nThe Standard Queen is perfect for enjoying your stay in Miami with all the comfort you need thanks to the queen-size bed and designer shower. Recharge your batteries with a snack from the minibar, discover the historic buildings of the Art Deco quarter and enjoy all the food and leisure on offer in the vicinity of the hotel.', 2, 0, 17, 1, 1, 0, '650.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:47:00'),
(42, 3, 102, 'For those who want space\r\n\r\nThe Standard King surrounds you with the elegance and unique design of Miami, and the comfort of a king-size bed. After an afternoon spent shopping on Lincoln Road, replenish your energy by having a snack from the minibar, relax in the designer shower, or get some rest in your large bed.', 2, 0, 17, 1, 0, 0, '650.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:47:24'),
(43, 3, 103, 'For those who love luxury\r\n\r\nIn our Presidential Suite you’ll have over 1,720square feet all to yourself. This is where you’ll spend your most luxurious vacation, with two whirlpool baths, one in the bathroom and the other on the balcony overlooking the sea. You’ll have plenty of places to unwind, whether on the outdoor sun loungers, in the living area or in the spacious bedroom. If you’re looking for luxury at Praia da Forte, this is it!', 4, 4, 18, 2, 0, 0, '1200.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:48:40'),
(44, 3, 104, 'For those who love luxury\r\n\r\nIn our Presidential Suite you’ll have over 1,720square feet all to yourself. This is where you’ll spend your most luxurious vacation, with two whirlpool baths, one in the bathroom and the other on the balcony overlooking the sea. You’ll have plenty of places to unwind, whether on the outdoor sun loungers, in the living area or in the spacious bedroom. If you’re looking for luxury at Praia da Forte, this is it!', 4, 4, 18, 2, 0, 0, '1200.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:48:45'),
(45, 3, 105, 'Apartment with sea views\r\n\r\nThe Oceanfront Superior Villa gives you space and views. Located on the top floor of the hotel, this apartment allows you to enjoy unbeatable, panoramic, Caribbean views. You’ll have a spacious lounge with kitchen, dining area, terrace and a separate bedroom', 2, 2, 24, 1, 1, 0, '800.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:50:47'),
(46, 3, 201, 'Apartment with sea views\r\n\r\nThe Oceanfront Superior Villa gives you space and views. Located on the top floor of the hotel, this apartment allows you to enjoy unbeatable, panoramic, Caribbean views. You’ll have a spacious lounge with kitchen, dining area, terrace and a separate bedroom', 2, 2, 24, 1, 0, 0, '800.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:50:52'),
(47, 3, 202, 'Apartment with sea views\r\n\r\nThe Oceanfront Superior Villa gives you space and views. Located on the top floor of the hotel, this apartment allows you to enjoy unbeatable, panoramic, Caribbean views. You’ll have a spacious lounge with kitchen, dining area, terrace and a separate bedroom', 2, 2, 24, 1, 0, 0, '800.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:50:57'),
(48, 3, 203, 'Apartment with sea views\r\n\r\nThe Oceanfront Superior Villa gives you space and views. Located on the top floor of the hotel, this apartment allows you to enjoy unbeatable, panoramic, Caribbean views. You’ll have a spacious lounge with kitchen, dining area, terrace and a separate bedroom', 2, 2, 24, 1, 0, 0, '800.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:51:06'),
(49, 3, 204, 'Apartment with sea views\r\n\r\nThe Oceanfront Superior Villa gives you space and views. Located on the top floor of the hotel, this apartment allows you to enjoy unbeatable, panoramic, Caribbean views. You’ll have a spacious lounge with kitchen, dining area, terrace and a separate bedroom.\r\n\r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nOF\r\n\r\n', 2, 2, 21, 1, 1, 0, '750.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:53:04'),
(50, 3, 205, 'Apartment with sea views\r\n\r\nThe Oceanfront Superior Villa gives you space and views. Located on the top floor of the hotel, this apartment allows you to enjoy unbeatable, panoramic, Caribbean views. You’ll have a spacious lounge with kitchen, dining area, terrace and a separate bedroom.\r\n\r\n \r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nOF\r\n', 2, 2, 21, 1, 1, 0, '750.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:53:42'),
(51, 3, 301, 'More room and sea views\r\n\r\nIn the Oceanfront Junior Suite​, you can sit on the living room sofa and watch the waves roll in and out for as long as you like. From the room’s private balcony, you’ll have views of the jungle surrounding the hotel. Inside the room, which is situated close to the beach and the pool, you can relax on the king-size bed, have a drink from the minibar and enjoy all the comforts we have provided to take care of you.', 2, 2, 21, 1, 0, 0, '750.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:56:26'),
(52, 3, 302, 'More room and sea views\r\n\r\nIn the Oceanfront Junior Suite​, you can sit on the living room sofa and watch the waves roll in and out for as long as you like. From the room’s private balcony, you’ll have views of the jungle surrounding the hotel. Inside the room, which is situated close to the beach and the pool, you can relax on the king-size bed, have a drink from the minibar and enjoy all the comforts we have provided to take care of you.', 2, 2, 21, 1, 0, 0, '750.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:56:34'),
(53, 3, 303, 'The utmost luxury experience in Puerto Ju\r\n\r\nIn the Presidential Suite, you can even enjoy your own private seaside pool! This is the hotel’s biggest and most elegant room, with 1239 sq ft split between a large bedroom with a king-size bed and a spacious living room with separate dining room and kitchen. You can have breakfast on the large terrace with direct access to the beach while listening to the waves breaking on the shore or watching your favorite show on the SmartTV. The bathroom features twin sinks and a shower.', 2, 0, 19, 2, 1, 0, '1050.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:59:22'),
(54, 3, 304, 'The utmost luxury experience in Puerto Ju\r\n\r\nIn the Presidential Suite, you can even enjoy your own private seaside pool! This is the hotel’s biggest and most elegant room, with 1239 sq ft split between a large bedroom with a king-size bed and a spacious living room with separate dining room and kitchen. You can have breakfast on the large terrace with direct access to the beach while listening to the waves breaking on the shore or watching your favorite show on the SmartTV. The bathroom features twin sinks and a shower.', 2, 0, 19, 2, 0, 0, '1050.00', NULL, '2019-11-27 09:36:53', '2019-12-11 17:59:34'),
(55, 3, 305, 'Exclusivity and ocean views right from your bed\r\n\r\nThe Premium Ocean Front Suite allows you to enjoy a panoramic view of the Dominican Caribbean from your king-size bed. Sea waves and palm trees will be the first thing you see when you open your eyes each morning. There’s also an adults-only private beach area for VIP guests like you.', 4, 4, 23, 1, 1, 0, '850.00', NULL, '2019-11-27 09:36:53', '2019-12-11 18:02:14'),
(56, 3, 401, 'Exclusivity and ocean views right from your bed\r\n\r\nThe Premium Ocean Front Suite allows you to enjoy a panoramic view of the Dominican Caribbean from your king-size bed. Sea waves and palm trees will be the first thing you see when you open your eyes each morning. There’s also an adults-only private beach area for VIP guests like you.', 4, 4, 23, 1, 1, 0, '850.00', NULL, '2019-11-27 09:36:53', '2019-12-11 18:02:19'),
(57, 3, 402, 'Exclusivity and ocean views right from your bed\r\n\r\nThe Premium Ocean Front Suite allows you to enjoy a panoramic view of the Dominican Caribbean from your king-size bed. Sea waves and palm trees will be the first thing you see when you open your eyes each morning. There’s also an adults-only private beach area for VIP guests like you.', 4, 4, 23, 1, 0, 0, '850.00', NULL, '2019-11-27 09:36:53', '2019-12-11 18:02:23'),
(58, 3, 403, 'Exclusivity and ocean views right from your bed\r\n\r\nThe Premium Ocean Front Suite allows you to enjoy a panoramic view of the Dominican Caribbean from your king-size bed. Sea waves and palm trees will be the first thing you see when you open your eyes each morning. There’s also an adults-only private beach area for VIP guests like you.', 4, 4, 23, 1, 0, 0, '850.00', NULL, '2019-11-27 09:36:53', '2019-12-11 18:02:28'),
(59, 3, 404, 'For those looking for something vast and modern\r\n\r\nTake advantage of vast new spaces in the Junior Deluxe Suite with a bedroom and living room and the comfort that comes from being in a refurbished area in the closest part of the complex to the ocean. They also come with their own concierge service where our staff will attend to your every need throughout your stay.', 1, 0, 25, 1, 0, 0, '480.00', NULL, '2019-11-27 09:36:53', '2019-12-11 18:03:03'),
(60, 3, 405, 'For those looking for more exclusivity\r\n\r\nThe Oceanfront Rooftop Corner Junior Suite is the most remarkable room in the entire hotel. From the rooftop pool, you’ll be able to take in unparalleled panoramic views of Cancún’s beaches. This spacious room, located on the hotel’s top floor, has all of the details to make your stay unforgettable. This well-appointed room features a premium minibar, smart TV, and spacious bathroom with bathtub and shower. You’ll also enjoy the convenience of a butler service at the hotel beach and pool, as well as room service, access to SPA Sensation’s hydrotherapy area, and wine pairing courses—all of which will make your vacation simply unforgettable. ', 2, 0, 22, 2, 0, 1, '1500.00', NULL, '2019-11-27 09:36:53', '2019-12-11 18:04:44'),
(61, 2, 102, 'For guests who want to be near the beach\r\n\r\nThe Superior Double room is located in the most coveted area of the hotel, offering you a retreat just steps away from the Caribbean waters. You can also spend time soaking in the SPA Sensations hydrotherapy pools, where you’ll enjoy complimentary access. You’ll also be able to take advantage of private check-in, beach towels in your room, and tons of other amenities that will make your vacation in the Dominican Republic an experience to remember.', 3, 2, 18, 2, 0, 1, '410.00', '2019-12-05 01:39:24', '2019-12-05 00:12:46', '2019-12-11 18:03:31');

--
-- Constraints for dumped tables
--

--
-- Constraints for table `rooms`
--
ALTER TABLE `rooms`
  ADD CONSTRAINT `fk_room_hotel` FOREIGN KEY (`hotel_id`) REFERENCES `hotels` (`id`),
  ADD CONSTRAINT `fk_room_room_type` FOREIGN KEY (`room_type_id`) REFERENCES `room_types` (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
